# List recipes
default:
    @just --list

# Generate examples/dev.tfrc with this checkout's absolute bin/ path
devrc:
    #!/usr/bin/env bash
    set -euo pipefail
    bin="$(pwd)/bin"
    cat > examples/dev.tfrc <<EOF
    # Generated by 'just devrc' — machine-specific, gitignored.
    # Usage (from examples/import-aliases or examples/data-source):
    #   TF_CLI_CONFIG_FILE=../dev.tfrc tofu plan
    # With dev_overrides, do NOT run 'tofu init' — plan/apply directly.
    provider_installation {
      dev_overrides {
        # OpenTofu resolves unprefixed sources to registry.opentofu.org;
        # Terraform resolves to registry.terraform.io. Override both.
        "registry.opentofu.org/laurigates/pfsense" = "${bin}"
        "registry.terraform.io/laurigates/pfsense" = "${bin}"
      }
      direct {}
    }
    EOF
    echo "wrote examples/dev.tfrc (dev_overrides -> ${bin})"

# Build the provider binary into bin/
build:
    go build -o bin/terraform-provider-pfsense .

# Run unit tests (httptest only — no live box)
test:
    go test ./...

# Regenerate provider code from spec/openapi.json
generate:
    python3 scripts/flatten_spec.py
    tfplugingen-openapi generate --config generator_config.yml --output provider-code-spec.json spec/openapi.flattened.json
    python3 scripts/patch_spec.py
    tfplugingen-framework generate all --input provider-code-spec.json --output internal/provider
    go build ./...
