// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_firewall_alias

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func FirewallAliasResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"address": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "Sets the host, network or port entries for the alias. When `type` is set to `host`, each\n                entry must be a valid IP address or FQDN. When `type` is set to `network`, each entry must be a valid\n                network CIDR or FQDN. When `type` is set to `port`, each entry must be a valid port or port range. You\n                may also specify an existing alias's `name` as an entry to created nested aliases.<br>",
				MarkdownDescription: "Sets the host, network or port entries for the alias. When `type` is set to `host`, each\n                entry must be a valid IP address or FQDN. When `type` is set to `network`, each entry must be a valid\n                network CIDR or FQDN. When `type` is set to `port`, each entry must be a valid port or port range. You\n                may also specify an existing alias's `name` as an entry to created nested aliases.<br>",
				Validators: []validator.List{
					listvalidator.SizeBetween(0, 128),
				},
			},
			"descr": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Sets a description to help specify the purpose or contents of the alias.<br>",
				MarkdownDescription: "Sets a description to help specify the purpose or contents of the alias.<br>",
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 1024),
				},
			},
			"detail": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "Sets descriptions for each alias `address`. Values must match the order of the `address` \n                value it relates to. For example, the first value specified here is the description for the first\n                value specified in the `address` field. This value cannot contain <br>",
				MarkdownDescription: "Sets descriptions for each alias `address`. Values must match the order of the `address` \n                value it relates to. For example, the first value specified here is the description for the first\n                value specified in the `address` field. This value cannot contain <br>",
				Validators: []validator.List{
					listvalidator.SizeBetween(0, 128),
				},
			},
			"id": schema.Int64Attribute{
				Computed:            true,
				Description:         "The ID of the object to target.",
				MarkdownDescription: "The ID of the object to target.",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Sets the name for the alias. This name must be unique from all other aliases.<br>",
				MarkdownDescription: "Sets the name for the alias. This name must be unique from all other aliases.<br>",
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 31),
				},
			},
			"type": schema.StringAttribute{
				Required:            true,
				Description:         "Sets the type of alias this object will be. This directly impacts what values can be\n                specified in the `address` field.<br>",
				MarkdownDescription: "Sets the type of alias this object will be. This directly impacts what values can be\n                specified in the `address` field.<br>",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"host",
						"network",
						"port",
					),
					stringvalidator.LengthBetween(0, 1024),
				},
			},
		},
	}
}

type FirewallAliasModel struct {
	Address types.List   `tfsdk:"address"`
	Descr   types.String `tfsdk:"descr"`
	Detail  types.List   `tfsdk:"detail"`
	Id      types.Int64  `tfsdk:"id"`
	Name    types.String `tfsdk:"name"`
	Type    types.String `tfsdk:"type"`
}
