// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_firewall_aliases

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func FirewallAliasesDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"data": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"address": schema.ListAttribute{
							ElementType:         types.StringType,
							Computed:            true,
							Description:         "Sets the host, network or port entries for the alias. When `type` is set to `host`, each\n                entry must be a valid IP address or FQDN. When `type` is set to `network`, each entry must be a valid\n                network CIDR or FQDN. When `type` is set to `port`, each entry must be a valid port or port range. You\n                may also specify an existing alias's `name` as an entry to created nested aliases.<br>",
							MarkdownDescription: "Sets the host, network or port entries for the alias. When `type` is set to `host`, each\n                entry must be a valid IP address or FQDN. When `type` is set to `network`, each entry must be a valid\n                network CIDR or FQDN. When `type` is set to `port`, each entry must be a valid port or port range. You\n                may also specify an existing alias's `name` as an entry to created nested aliases.<br>",
						},
						"descr": schema.StringAttribute{
							Computed:            true,
							Description:         "Sets a description to help specify the purpose or contents of the alias.<br>",
							MarkdownDescription: "Sets a description to help specify the purpose or contents of the alias.<br>",
						},
						"detail": schema.ListAttribute{
							ElementType:         types.StringType,
							Computed:            true,
							Description:         "Sets descriptions for each alias `address`. Values must match the order of the `address` \n                value it relates to. For example, the first value specified here is the description for the first\n                value specified in the `address` field. This value cannot contain <br>",
							MarkdownDescription: "Sets descriptions for each alias `address`. Values must match the order of the `address` \n                value it relates to. For example, the first value specified here is the description for the first\n                value specified in the `address` field. This value cannot contain <br>",
						},
						"name": schema.StringAttribute{
							Computed:            true,
							Description:         "Sets the name for the alias. This name must be unique from all other aliases.<br>",
							MarkdownDescription: "Sets the name for the alias. This name must be unique from all other aliases.<br>",
						},
						"type": schema.StringAttribute{
							Computed:            true,
							Description:         "Sets the type of alias this object will be. This directly impacts what values can be\n                specified in the `address` field.<br>",
							MarkdownDescription: "Sets the type of alias this object will be. This directly impacts what values can be\n                specified in the `address` field.<br>",
						},
					},
					CustomType: DataType{
						ObjectType: types.ObjectType{
							AttrTypes: DataValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
		},
	}
}

type FirewallAliasesModel struct {
	Data types.List `tfsdk:"data"`
}

var _ basetypes.ObjectTypable = DataType{}

type DataType struct {
	basetypes.ObjectType
}

func (t DataType) Equal(o attr.Type) bool {
	other, ok := o.(DataType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DataType) String() string {
	return "DataType"
}

func (t DataType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	addressAttribute, ok := attributes["address"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`address is missing from object`)

		return nil, diags
	}

	addressVal, ok := addressAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`address expected to be basetypes.ListValue, was: %T`, addressAttribute))
	}

	descrAttribute, ok := attributes["descr"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`descr is missing from object`)

		return nil, diags
	}

	descrVal, ok := descrAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`descr expected to be basetypes.StringValue, was: %T`, descrAttribute))
	}

	detailAttribute, ok := attributes["detail"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`detail is missing from object`)

		return nil, diags
	}

	detailVal, ok := detailAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`detail expected to be basetypes.ListValue, was: %T`, detailAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DataValue{
		Address:  addressVal,
		Descr:    descrVal,
		Detail:   detailVal,
		Name:     nameVal,
		DataType: typeVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewDataValueNull() DataValue {
	return DataValue{
		state: attr.ValueStateNull,
	}
}

func NewDataValueUnknown() DataValue {
	return DataValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDataValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DataValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DataValue Attribute Value",
				"While creating a DataValue value, a missing attribute value was detected. "+
					"A DataValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DataValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DataValue Attribute Type",
				"While creating a DataValue value, an invalid attribute value was detected. "+
					"A DataValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DataValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DataValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DataValue Attribute Value",
				"While creating a DataValue value, an extra attribute value was detected. "+
					"A DataValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DataValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDataValueUnknown(), diags
	}

	addressAttribute, ok := attributes["address"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`address is missing from object`)

		return NewDataValueUnknown(), diags
	}

	addressVal, ok := addressAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`address expected to be basetypes.ListValue, was: %T`, addressAttribute))
	}

	descrAttribute, ok := attributes["descr"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`descr is missing from object`)

		return NewDataValueUnknown(), diags
	}

	descrVal, ok := descrAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`descr expected to be basetypes.StringValue, was: %T`, descrAttribute))
	}

	detailAttribute, ok := attributes["detail"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`detail is missing from object`)

		return NewDataValueUnknown(), diags
	}

	detailVal, ok := detailAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`detail expected to be basetypes.ListValue, was: %T`, detailAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewDataValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewDataValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewDataValueUnknown(), diags
	}

	return DataValue{
		Address:  addressVal,
		Descr:    descrVal,
		Detail:   detailVal,
		Name:     nameVal,
		DataType: typeVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewDataValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DataValue {
	object, diags := NewDataValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewDataValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DataType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDataValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDataValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDataValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDataValueMust(DataValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DataType) ValueType(ctx context.Context) attr.Value {
	return DataValue{}
}

var _ basetypes.ObjectValuable = DataValue{}

type DataValue struct {
	Address  basetypes.ListValue   `tfsdk:"address"`
	Descr    basetypes.StringValue `tfsdk:"descr"`
	Detail   basetypes.ListValue   `tfsdk:"detail"`
	Name     basetypes.StringValue `tfsdk:"name"`
	DataType basetypes.StringValue `tfsdk:"type"`
	state    attr.ValueState
}

func (v DataValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 5)

	var val tftypes.Value
	var err error

	attrTypes["address"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["descr"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["detail"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 5)

		val, err = v.Address.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["address"] = val

		val, err = v.Descr.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["descr"] = val

		val, err = v.Detail.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["detail"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.DataType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DataValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DataValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DataValue) String() string {
	return "DataValue"
}

func (v DataValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var addressVal basetypes.ListValue
	switch {
	case v.Address.IsUnknown():
		addressVal = types.ListUnknown(types.StringType)
	case v.Address.IsNull():
		addressVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		addressVal, d = types.ListValue(types.StringType, v.Address.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"address": basetypes.ListType{
				ElemType: types.StringType,
			},
			"descr": basetypes.StringType{},
			"detail": basetypes.ListType{
				ElemType: types.StringType,
			},
			"name": basetypes.StringType{},
			"type": basetypes.StringType{},
		}), diags
	}

	var detailVal basetypes.ListValue
	switch {
	case v.Detail.IsUnknown():
		detailVal = types.ListUnknown(types.StringType)
	case v.Detail.IsNull():
		detailVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		detailVal, d = types.ListValue(types.StringType, v.Detail.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"address": basetypes.ListType{
				ElemType: types.StringType,
			},
			"descr": basetypes.StringType{},
			"detail": basetypes.ListType{
				ElemType: types.StringType,
			},
			"name": basetypes.StringType{},
			"type": basetypes.StringType{},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"address": basetypes.ListType{
			ElemType: types.StringType,
		},
		"descr": basetypes.StringType{},
		"detail": basetypes.ListType{
			ElemType: types.StringType,
		},
		"name": basetypes.StringType{},
		"type": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"address": addressVal,
			"descr":   v.Descr,
			"detail":  detailVal,
			"name":    v.Name,
			"type":    v.DataType,
		})

	return objVal, diags
}

func (v DataValue) Equal(o attr.Value) bool {
	other, ok := o.(DataValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Address.Equal(other.Address) {
		return false
	}

	if !v.Descr.Equal(other.Descr) {
		return false
	}

	if !v.Detail.Equal(other.Detail) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.DataType.Equal(other.DataType) {
		return false
	}

	return true
}

func (v DataValue) Type(ctx context.Context) attr.Type {
	return DataType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DataValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"address": basetypes.ListType{
			ElemType: types.StringType,
		},
		"descr": basetypes.StringType{},
		"detail": basetypes.ListType{
			ElemType: types.StringType,
		},
		"name": basetypes.StringType{},
		"type": basetypes.StringType{},
	}
}
