// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_pfsense

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func PfsenseProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type PfsenseModel struct {
}
