// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_firewall_nat_one_to_one_mapping

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func FirewallNatOneToOneMappingResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"apply_immediately": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Whether to apply the staged change to the running firewall immediately after this resource is created, updated, or deleted. Defaults to true. Set to false to batch multiple changes and apply them separately.",
				MarkdownDescription: "Whether to apply the staged change to the running firewall immediately after this resource is created, updated, or deleted. Defaults to true. Set to false to batch multiple changes and apply them separately.",
				Default:             booldefault.StaticBool(true),
			},
			"descr": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "A description for this 1:1 NAT mapping<br>",
				MarkdownDescription: "A description for this 1:1 NAT mapping<br>",
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 1024),
				},
			},
			"destination": schema.StringAttribute{
				Required:            true,
				Description:         "The destination IP address or subnet that traffic must match to apply this mapping. Valid value options are: an existing interface, an IP address, a subnet CIDR, an existing alias, `any`, `l2tp`, `pppoe`. The context of this address can be inverted by prefixing the value with `!`. For interface values, the `:ip`  modifier can be appended to the value to use the interface's IP address instead of its entire subnet.<br>",
				MarkdownDescription: "The destination IP address or subnet that traffic must match to apply this mapping. Valid value options are: an existing interface, an IP address, a subnet CIDR, an existing alias, `any`, `l2tp`, `pppoe`. The context of this address can be inverted by prefixing the value with `!`. For interface values, the `:ip`  modifier can be appended to the value to use the interface's IP address instead of its entire subnet.<br>",
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 1024),
				},
			},
			"disabled": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Disables this 1:1 NAT mapping.<br>",
				MarkdownDescription: "Disables this 1:1 NAT mapping.<br>",
			},
			"external": schema.StringAttribute{
				Required:            true,
				Description:         "The external IP address or interface for the 1:1 mapping. Valid value options are: an IP address. For interface values, the `:ip`  modifier can be appended to the value to use the interface's IP address instead of its entire subnet.<br>",
				MarkdownDescription: "The external IP address or interface for the 1:1 mapping. Valid value options are: an IP address. For interface values, the `:ip`  modifier can be appended to the value to use the interface's IP address instead of its entire subnet.<br>",
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 1024),
				},
			},
			"id": schema.Int64Attribute{
				Computed:            true,
				Description:         "The ID of the object to target.",
				MarkdownDescription: "The ID of the object to target.",
			},
			"interface": schema.StringAttribute{
				Required:            true,
				Description:         "The interface this 1:1 NAT mapping applies to.<br>",
				MarkdownDescription: "The interface this 1:1 NAT mapping applies to.<br>",
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 1024),
				},
			},
			"ipprotocol": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The IP version this mapping applies to.<br>",
				MarkdownDescription: "The IP version this mapping applies to.<br>",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"inet",
						"inet6",
					),
					stringvalidator.LengthBetween(0, 1024),
				},
				Default: stringdefault.StaticString("inet"),
			},
			"natreflection": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Enables or disables NAT reflection for traffic matching this mapping. Set to `null` to use the system default.<br>",
				MarkdownDescription: "Enables or disables NAT reflection for traffic matching this mapping. Set to `null` to use the system default.<br>",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"enable",
						"disable",
					),
					stringvalidator.LengthBetween(0, 1024),
				},
			},
			"nobinat": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Exclude traffic matching this mapping from a later, more general, mapping.<br>",
				MarkdownDescription: "Exclude traffic matching this mapping from a later, more general, mapping.<br>",
			},
			"source": schema.StringAttribute{
				Required:            true,
				Description:         "The source IP address or subnet that traffic must match to apply this mapping. Valid value options are: an existing interface, an IP address, a subnet CIDR, `any`, `l2tp`, `pppoe`. The context of this address can be inverted by prefixing the value with `!`. For interface values, the `:ip`  modifier can be appended to the value to use the interface's IP address instead of its entire subnet.<br>",
				MarkdownDescription: "The source IP address or subnet that traffic must match to apply this mapping. Valid value options are: an existing interface, an IP address, a subnet CIDR, `any`, `l2tp`, `pppoe`. The context of this address can be inverted by prefixing the value with `!`. For interface values, the `:ip`  modifier can be appended to the value to use the interface's IP address instead of its entire subnet.<br>",
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 1024),
				},
			},
		},
	}
}

type FirewallNatOneToOneMappingModel struct {
	ApplyImmediately types.Bool   `tfsdk:"apply_immediately"`
	Descr            types.String `tfsdk:"descr"`
	Destination      types.String `tfsdk:"destination"`
	Disabled         types.Bool   `tfsdk:"disabled"`
	External         types.String `tfsdk:"external"`
	Id               types.Int64  `tfsdk:"id"`
	Interface        types.String `tfsdk:"interface"`
	Ipprotocol       types.String `tfsdk:"ipprotocol"`
	Natreflection    types.String `tfsdk:"natreflection"`
	Nobinat          types.Bool   `tfsdk:"nobinat"`
	Source           types.String `tfsdk:"source"`
}
