// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_firewall_nat_outbound_mapping

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func FirewallNatOutboundMappingResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"apply_immediately": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Whether to apply the staged change to the running firewall immediately after this resource is created, updated, or deleted. Defaults to true. Set to false to batch multiple changes and apply them separately.",
				MarkdownDescription: "Whether to apply the staged change to the running firewall immediately after this resource is created, updated, or deleted. Defaults to true. Set to false to batch multiple changes and apply them separately.",
				Default:             booldefault.StaticBool(true),
			},
			"descr": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "A description for the outbound NAT mapping.<br>",
				MarkdownDescription: "A description for the outbound NAT mapping.<br>",
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 1024),
				},
			},
			"destination": schema.StringAttribute{
				Required:            true,
				Description:         "The destination network this rule should match. Valid value options are: an existing interface, a subnet CIDR, an existing alias, `any`, `pppoe`. The context of this address can be inverted by prefixing the value with `!`. For interface values, the `:ip`  modifier can be appended to the value to use the interface's IP address instead of its entire subnet.<br>",
				MarkdownDescription: "The destination network this rule should match. Valid value options are: an existing interface, a subnet CIDR, an existing alias, `any`, `pppoe`. The context of this address can be inverted by prefixing the value with `!`. For interface values, the `:ip`  modifier can be appended to the value to use the interface's IP address instead of its entire subnet.<br>",
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 1024),
				},
			},
			"destination_port": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The destination port this rule should match. Valid options are: a TCP/UDP port number, a TCP/UDP port range separated by `:`, an existing port type firewall alias<br>",
				MarkdownDescription: "The destination port this rule should match. Valid options are: a TCP/UDP port number, a TCP/UDP port range separated by `:`, an existing port type firewall alias<br>",
			},
			"disabled": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Disable this outbound NAT rule.<br>",
				MarkdownDescription: "Disable this outbound NAT rule.<br>",
			},
			"id": schema.Int64Attribute{
				Computed:            true,
				Description:         "The ID of the object to target.",
				MarkdownDescription: "The ID of the object to target.",
			},
			"interface": schema.StringAttribute{
				Required:            true,
				Description:         "The interface on which traffic is matched as it exits the firewall. In most cases this is a WAN-type or another externally-connected interface.<br>",
				MarkdownDescription: "The interface on which traffic is matched as it exits the firewall. In most cases this is a WAN-type or another externally-connected interface.<br>",
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 1024),
				},
			},
			"nat_port": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The external source port or port range used for rewriting the original source port on connections matching the rule. Valid options are: a TCP/UDP port number, a TCP/UDP port range separated by `:`<br><br>This field is only available when the following conditions are met:<br>- `static_nat_port` must be equal to `false`<br>- `nonat` must be equal to `false`<br>",
				MarkdownDescription: "The external source port or port range used for rewriting the original source port on connections matching the rule. Valid options are: a TCP/UDP port number, a TCP/UDP port range separated by `:`<br><br>This field is only available when the following conditions are met:<br>- `static_nat_port` must be equal to `false`<br>- `nonat` must be equal to `false`<br>",
			},
			"nonat": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Do not NAT traffic matching this rule.<br>",
				MarkdownDescription: "Do not NAT traffic matching this rule.<br>",
			},
			"nosync": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Do not sync this rule to HA peers.<br>",
				MarkdownDescription: "Do not sync this rule to HA peers.<br>",
			},
			"poolopts": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The pool option used to load balance external IP mapping when `target` is set to a subnet or alias of many addresses. Set to `null` to revert to the system default.<br><br>This field is only available when the following conditions are met:<br>- `nonat` must be equal to `false`<br>",
				MarkdownDescription: "The pool option used to load balance external IP mapping when `target` is set to a subnet or alias of many addresses. Set to `null` to revert to the system default.<br><br>This field is only available when the following conditions are met:<br>- `nonat` must be equal to `false`<br>",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"round-robin",
						"round-robin sticky-address",
						"random",
						"random sticky-address",
						"source-hash",
						"bitmask",
					),
					stringvalidator.LengthBetween(0, 1024),
				},
			},
			"protocol": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The protocol this rule should match. Use `null` for any protocol.<br>",
				MarkdownDescription: "The protocol this rule should match. Use `null` for any protocol.<br>",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"tcp",
						"udp",
						"tcp/udp",
						"icmp",
						"esp",
						"ah",
						"gre",
						"ipv6",
						"igmp",
						"pim",
						"ospf",
					),
					stringvalidator.LengthBetween(0, 1024),
				},
			},
			"source": schema.StringAttribute{
				Required:            true,
				Description:         "The source network this rule should match. Valid value options are: an existing interface, a subnet CIDR, an existing alias, `any`, `(self)`, `pppoe`. The context of this address can be inverted by prefixing the value with `!`. For interface values, the `:ip`  modifier can be appended to the value to use the interface's IP address instead of its entire subnet.<br>",
				MarkdownDescription: "The source network this rule should match. Valid value options are: an existing interface, a subnet CIDR, an existing alias, `any`, `(self)`, `pppoe`. The context of this address can be inverted by prefixing the value with `!`. For interface values, the `:ip`  modifier can be appended to the value to use the interface's IP address instead of its entire subnet.<br>",
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 1024),
				},
			},
			"source_hash_key": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The key that is fed to the hashing algorithm in hex format. This must be a 16 byte (32 character) hex string prefixed with `0x`. If a value is not provided, one will automatically be generated<br><br>This field is only available when the following conditions are met:<br>- `poolopts` must be equal to `'source-hash'`<br>- `nonat` must be equal to `false`<br>",
				MarkdownDescription: "The key that is fed to the hashing algorithm in hex format. This must be a 16 byte (32 character) hex string prefixed with `0x`. If a value is not provided, one will automatically be generated<br><br>This field is only available when the following conditions are met:<br>- `poolopts` must be equal to `'source-hash'`<br>- `nonat` must be equal to `false`<br>",
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 1024),
				},
				Default: stringdefault.StaticString("0xbcff6ac603ff46e20275fcc683d72632"),
			},
			"source_port": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The source port this rule should match. Valid options are: a TCP/UDP port number, a TCP/UDP port range separated by `:`, an existing port type firewall alias<br>",
				MarkdownDescription: "The source port this rule should match. Valid options are: a TCP/UDP port number, a TCP/UDP port range separated by `:`, an existing port type firewall alias<br>",
			},
			"static_nat_port": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Do not rewrite source port for traffic matching this rule.<br><br>This field is only available when the following conditions are met:<br>- `nonat` must be equal to `false`<br>",
				MarkdownDescription: "Do not rewrite source port for traffic matching this rule.<br><br>This field is only available when the following conditions are met:<br>- `nonat` must be equal to `false`<br>",
			},
			"target": schema.StringAttribute{
				Required:            true,
				Description:         "The target network traffic matching this rule should be translated to. Valid value options are: an IP address, an existing alias. For interface values, the `:ip`  modifier can be appended to the value to use the interface's IP address instead of its entire subnet.<br><br>This field is only available when the following conditions are met:<br>- `nonat` must be equal to `false`<br>",
				MarkdownDescription: "The target network traffic matching this rule should be translated to. Valid value options are: an IP address, an existing alias. For interface values, the `:ip`  modifier can be appended to the value to use the interface's IP address instead of its entire subnet.<br><br>This field is only available when the following conditions are met:<br>- `nonat` must be equal to `false`<br>",
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 1024),
				},
			},
			"target_subnet": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The subnet bits for the assigned `target`. This field is only applicable if `target` is set to an IP address. This has no affect for alias or interface `targets`.<br><br>This field is only available when the following conditions are met:<br>- `nonat` must be equal to `false`<br>",
				MarkdownDescription: "The subnet bits for the assigned `target`. This field is only applicable if `target` is set to an IP address. This has no affect for alias or interface `targets`.<br><br>This field is only available when the following conditions are met:<br>- `nonat` must be equal to `false`<br>",
				Validators: []validator.Int64{
					int64validator.Between(1, 128),
				},
				Default: int64default.StaticInt64(128),
			},
		},
	}
}

type FirewallNatOutboundMappingModel struct {
	ApplyImmediately types.Bool   `tfsdk:"apply_immediately"`
	Descr            types.String `tfsdk:"descr"`
	Destination      types.String `tfsdk:"destination"`
	DestinationPort  types.String `tfsdk:"destination_port"`
	Disabled         types.Bool   `tfsdk:"disabled"`
	Id               types.Int64  `tfsdk:"id"`
	Interface        types.String `tfsdk:"interface"`
	NatPort          types.String `tfsdk:"nat_port"`
	Nonat            types.Bool   `tfsdk:"nonat"`
	Nosync           types.Bool   `tfsdk:"nosync"`
	Poolopts         types.String `tfsdk:"poolopts"`
	Protocol         types.String `tfsdk:"protocol"`
	Source           types.String `tfsdk:"source"`
	SourceHashKey    types.String `tfsdk:"source_hash_key"`
	SourcePort       types.String `tfsdk:"source_port"`
	StaticNatPort    types.Bool   `tfsdk:"static_nat_port"`
	Target           types.String `tfsdk:"target"`
	TargetSubnet     types.Int64  `tfsdk:"target_subnet"`
}
