// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_firewall_nat_port_forward

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func FirewallNatPortForwardResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"apply_immediately": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Whether to apply the staged change to the running firewall immediately after this resource is created, updated, or deleted. Defaults to true. Set to false to batch multiple changes and apply them separately.",
				MarkdownDescription: "Whether to apply the staged change to the running firewall immediately after this resource is created, updated, or deleted. Defaults to true. Set to false to batch multiple changes and apply them separately.",
				Default:             booldefault.StaticBool(true),
			},
			"associated_rule_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The associated firewall rule mode. Use an empty string to require a separate firewall rule to be created to pass traffic matching this port forward rule. Use `new` to create a new associated firewall rule to pass traffic matching this port forward rule. Use `pass` to automatically pass traffic matching this port forward rule without the need for a firewall rule.   Otherwise, you can specify the `associated_rule_id` of an existing firewall rule to associate with this port forward rule.<br>",
				MarkdownDescription: "The associated firewall rule mode. Use an empty string to require a separate firewall rule to be created to pass traffic matching this port forward rule. Use `new` to create a new associated firewall rule to pass traffic matching this port forward rule. Use `pass` to automatically pass traffic matching this port forward rule without the need for a firewall rule.   Otherwise, you can specify the `associated_rule_id` of an existing firewall rule to associate with this port forward rule.<br>",
			},
			"created_by": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The username and IP of the user who originally created this port forward rule.<br>",
				MarkdownDescription: "The username and IP of the user who originally created this port forward rule.<br>",
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 1024),
				},
				Default: stringdefault.StaticString("@unknown IP (API)"),
			},
			"created_time": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The unix timestamp of when this port forward rule was original created.<br>",
				MarkdownDescription: "The unix timestamp of when this port forward rule was original created.<br>",
				Validators: []validator.Int64{
					int64validator.Between(0, 99999999999999),
				},
			},
			"descr": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "A description for this port forward rule.<br>",
				MarkdownDescription: "A description for this port forward rule.<br>",
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 1024),
				},
			},
			"destination": schema.StringAttribute{
				Required:            true,
				Description:         "The destination address this rule applies to. Valid value options are: an existing interface, an IP address, a subnet CIDR, an existing alias, `any`, `(self)`, `l2tp`, `pppoe`. The context of this address can be inverted by prefixing the value with `!`. For interface values, the `:ip`  modifier can be appended to the value to use the interface's IP address instead of its entire subnet.<br>",
				MarkdownDescription: "The destination address this rule applies to. Valid value options are: an existing interface, an IP address, a subnet CIDR, an existing alias, `any`, `(self)`, `l2tp`, `pppoe`. The context of this address can be inverted by prefixing the value with `!`. For interface values, the `:ip`  modifier can be appended to the value to use the interface's IP address instead of its entire subnet.<br>",
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 1024),
				},
			},
			"destination_port": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The destination port this port forward rule applies to. Set to `null` to allow any destination port. Valid options are: a TCP/UDP port number, a TCP/UDP port range separated by `:`, an existing port type firewall alias<br><br>This field is only available when the following conditions are met:<br>- `protocol` must be one of [ tcp, udp, tcp/udp ]<br>",
				MarkdownDescription: "The destination port this port forward rule applies to. Set to `null` to allow any destination port. Valid options are: a TCP/UDP port number, a TCP/UDP port range separated by `:`, an existing port type firewall alias<br><br>This field is only available when the following conditions are met:<br>- `protocol` must be one of [ tcp, udp, tcp/udp ]<br>",
			},
			"disabled": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Disables this port forward rule.<br>",
				MarkdownDescription: "Disables this port forward rule.<br>",
			},
			"id": schema.Int64Attribute{
				Computed:            true,
				Description:         "The ID of the object to target.",
				MarkdownDescription: "The ID of the object to target.",
			},
			"interface": schema.StringAttribute{
				Required:            true,
				Description:         "The interface this port forward rule applies to.<br>",
				MarkdownDescription: "The interface this port forward rule applies to.<br>",
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 1024),
				},
			},
			"ipprotocol": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The IP protocol this port forward rule should match.<br>",
				MarkdownDescription: "The IP protocol this port forward rule should match.<br>",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"inet",
						"inet6",
						"inet46",
					),
					stringvalidator.LengthBetween(0, 1024),
				},
				Default: stringdefault.StaticString("inet"),
			},
			"local_port": schema.StringAttribute{
				Required:            true,
				Description:         "The port on the internal host to forward matching traffic to. In most cases, this must match the `destination_port` value. In the event that the `desintation_port` is a range, this value should be the first value in that range. Valid options are: a TCP/UDP port number, an existing port type firewall alias<br><br>This field is only available when the following conditions are met:<br>- `protocol` must be one of [ tcp, udp, tcp/udp ]<br>",
				MarkdownDescription: "The port on the internal host to forward matching traffic to. In most cases, this must match the `destination_port` value. In the event that the `desintation_port` is a range, this value should be the first value in that range. Valid options are: a TCP/UDP port number, an existing port type firewall alias<br><br>This field is only available when the following conditions are met:<br>- `protocol` must be one of [ tcp, udp, tcp/udp ]<br>",
			},
			"natreflection": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The NAT reflection mode to use for traffic matching this port forward rule. Set to `null` to use the system default.<br>",
				MarkdownDescription: "The NAT reflection mode to use for traffic matching this port forward rule. Set to `null` to use the system default.<br>",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"enable",
						"disable",
						"purenat",
					),
					stringvalidator.LengthBetween(0, 1024),
				},
			},
			"nordr": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Disables redirection for traffic matching this rule.<br>",
				MarkdownDescription: "Disables redirection for traffic matching this rule.<br>",
			},
			"nosync": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Prevents this port forward rule from being synced to non-primary CARP members.<br>",
				MarkdownDescription: "Prevents this port forward rule from being synced to non-primary CARP members.<br>",
			},
			"protocol": schema.StringAttribute{
				Required:            true,
				Description:         "The IP/transport protocol this port forward rule should match.<br>",
				MarkdownDescription: "The IP/transport protocol this port forward rule should match.<br>",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"tcp",
						"udp",
						"tcp/udp",
						"icmp",
						"esp",
						"ah",
						"gre",
						"ipv6",
						"igmp",
						"pim",
						"ospf",
					),
					stringvalidator.LengthBetween(0, 1024),
				},
			},
			"source": schema.StringAttribute{
				Required:            true,
				Description:         "The source address this port forward rule applies to. Valid value options are: an existing interface, an IP address, a subnet CIDR, an existing alias, `any`, `(self)`, `l2tp`, `pppoe`. The context of this address can be inverted by prefixing the value with `!`. For interface values, the `:ip`  modifier can be appended to the value to use the interface's IP address instead of its entire subnet.<br>",
				MarkdownDescription: "The source address this port forward rule applies to. Valid value options are: an existing interface, an IP address, a subnet CIDR, an existing alias, `any`, `(self)`, `l2tp`, `pppoe`. The context of this address can be inverted by prefixing the value with `!`. For interface values, the `:ip`  modifier can be appended to the value to use the interface's IP address instead of its entire subnet.<br>",
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 1024),
				},
			},
			"source_port": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The source port this port forward rule applies to. Set to `null` to allow any source port. Valid options are: a TCP/UDP port number, a TCP/UDP port range separated by `:`, an existing port type firewall alias<br><br>This field is only available when the following conditions are met:<br>- `protocol` must be one of [ tcp, udp, tcp/udp ]<br>",
				MarkdownDescription: "The source port this port forward rule applies to. Set to `null` to allow any source port. Valid options are: a TCP/UDP port number, a TCP/UDP port range separated by `:`, an existing port type firewall alias<br><br>This field is only available when the following conditions are met:<br>- `protocol` must be one of [ tcp, udp, tcp/udp ]<br>",
			},
			"target": schema.StringAttribute{
				Required:            true,
				Description:         "The IP address or alias of the internal host to forward matching traffic to.<br>",
				MarkdownDescription: "The IP address or alias of the internal host to forward matching traffic to.<br>",
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 1024),
				},
			},
			"updated_by": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The username and IP of the user who last updated this port forward rule.<br>",
				MarkdownDescription: "The username and IP of the user who last updated this port forward rule.<br>",
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 1024),
				},
				Default: stringdefault.StaticString("@unknown IP (API)"),
			},
			"updated_time": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The unix timestamp of when this port forward rule was original created.<br>",
				MarkdownDescription: "The unix timestamp of when this port forward rule was original created.<br>",
				Validators: []validator.Int64{
					int64validator.Between(0, 99999999999999),
				},
			},
		},
	}
}

type FirewallNatPortForwardModel struct {
	ApplyImmediately types.Bool   `tfsdk:"apply_immediately"`
	AssociatedRuleId types.String `tfsdk:"associated_rule_id"`
	CreatedBy        types.String `tfsdk:"created_by"`
	CreatedTime      types.Int64  `tfsdk:"created_time"`
	Descr            types.String `tfsdk:"descr"`
	Destination      types.String `tfsdk:"destination"`
	DestinationPort  types.String `tfsdk:"destination_port"`
	Disabled         types.Bool   `tfsdk:"disabled"`
	Id               types.Int64  `tfsdk:"id"`
	Interface        types.String `tfsdk:"interface"`
	Ipprotocol       types.String `tfsdk:"ipprotocol"`
	LocalPort        types.String `tfsdk:"local_port"`
	Natreflection    types.String `tfsdk:"natreflection"`
	Nordr            types.Bool   `tfsdk:"nordr"`
	Nosync           types.Bool   `tfsdk:"nosync"`
	Protocol         types.String `tfsdk:"protocol"`
	Source           types.String `tfsdk:"source"`
	SourcePort       types.String `tfsdk:"source_port"`
	Target           types.String `tfsdk:"target"`
	UpdatedBy        types.String `tfsdk:"updated_by"`
	UpdatedTime      types.Int64  `tfsdk:"updated_time"`
}
