// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_firewall_rule

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func FirewallRuleResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"ackqueue": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The name of the traffic shaper queue to assume as the ACK queue for ACK traffic matching this rule.<br>",
				MarkdownDescription: "The name of the traffic shaper queue to assume as the ACK queue for ACK traffic matching this rule.<br>",
			},
			"apply_immediately": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Whether to apply the staged change to the running firewall immediately after this resource is created, updated, or deleted. Defaults to true. Set to false to batch multiple changes and apply them separately.",
				MarkdownDescription: "Whether to apply the staged change to the running firewall immediately after this resource is created, updated, or deleted. Defaults to true. Set to false to batch multiple changes and apply them separately.",
				Default:             booldefault.StaticBool(true),
			},
			"associated_rule_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The internal rule ID for the NAT rule associated with this rule.<br>",
				MarkdownDescription: "The internal rule ID for the NAT rule associated with this rule.<br>",
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 1024),
				},
			},
			"created_by": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The username and IP of the user who originally created this firewall rule.<br>",
				MarkdownDescription: "The username and IP of the user who originally created this firewall rule.<br>",
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 1024),
				},
				Default: stringdefault.StaticString("@unknown IP (API)"),
			},
			"created_time": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The unix timestamp of when this firewall rule was original created.<br>",
				MarkdownDescription: "The unix timestamp of when this firewall rule was original created.<br>",
				Validators: []validator.Int64{
					int64validator.Between(0, 99999999999999),
				},
			},
			"defaultqueue": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The name of the traffic shaper queue to assume as the default queue for traffic matching this rule.<br>",
				MarkdownDescription: "The name of the traffic shaper queue to assume as the default queue for traffic matching this rule.<br>",
			},
			"descr": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "A description detailing the purpose or justification of this firewall rule.<br>",
				MarkdownDescription: "A description detailing the purpose or justification of this firewall rule.<br>",
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 1024),
				},
			},
			"destination": schema.StringAttribute{
				Required:            true,
				Description:         "The destination address this rule applies to. Valid value options are: an existing interface, an IP address, a subnet CIDR, an existing alias, `any`, `(self)`, `l2tp`, `pppoe`. The context of this address can be inverted by prefixing the value with `!`. For interface values, the `:ip`  modifier can be appended to the value to use the interface's IP address instead of its entire subnet.<br>",
				MarkdownDescription: "The destination address this rule applies to. Valid value options are: an existing interface, an IP address, a subnet CIDR, an existing alias, `any`, `(self)`, `l2tp`, `pppoe`. The context of this address can be inverted by prefixing the value with `!`. For interface values, the `:ip`  modifier can be appended to the value to use the interface's IP address instead of its entire subnet.<br>",
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 1024),
				},
			},
			"destination_port": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The destination port this rule applies to. Set to `null` to allow any destination port. Valid options are: a TCP/UDP port number, a TCP/UDP port range separated by `:`, an existing port type firewall alias<br><br>This field is only available when the following conditions are met:<br>- `protocol` must be one of [ tcp, udp, tcp/udp ]<br>",
				MarkdownDescription: "The destination port this rule applies to. Set to `null` to allow any destination port. Valid options are: a TCP/UDP port number, a TCP/UDP port range separated by `:`, an existing port type firewall alias<br><br>This field is only available when the following conditions are met:<br>- `protocol` must be one of [ tcp, udp, tcp/udp ]<br>",
			},
			"direction": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The direction of traffic this firewall rule applies to. This field only applies to floating firewall rules.<br><br>This field is only available when the following conditions are met:<br>- `floating` must be equal to `true`<br>",
				MarkdownDescription: "The direction of traffic this firewall rule applies to. This field only applies to floating firewall rules.<br><br>This field is only available when the following conditions are met:<br>- `floating` must be equal to `true`<br>",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"any",
						"in",
						"out",
					),
					stringvalidator.LengthBetween(0, 1024),
				},
				Default: stringdefault.StaticString("any"),
			},
			"disabled": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Enable or disable this firewall rule.<br>",
				MarkdownDescription: "Enable or disable this firewall rule.<br>",
			},
			"dnpipe": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The name of the traffic shaper limiter pipe or queue to use for incoming traffic.<br>",
				MarkdownDescription: "The name of the traffic shaper limiter pipe or queue to use for incoming traffic.<br>",
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 1024),
				},
			},
			"floating": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Mark this rule as a floating firewall rule.<br>",
				MarkdownDescription: "Mark this rule as a floating firewall rule.<br>",
			},
			"gateway": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The gateway traffic matching this rule will be routed to. Set to `null` to use default.<br>",
				MarkdownDescription: "The gateway traffic matching this rule will be routed to. Set to `null` to use default.<br>",
			},
			"icmptype": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "Th ICMP subtypes this rule applies to. This field is only applicable when `ipprotocol` is `inet` and `protocol` is `icmp`.<br><br>This field is only available when the following conditions are met:<br>- `protocol` must be equal to `'icmp'`<br>",
				MarkdownDescription: "Th ICMP subtypes this rule applies to. This field is only applicable when `ipprotocol` is `inet` and `protocol` is `icmp`.<br><br>This field is only available when the following conditions are met:<br>- `protocol` must be equal to `'icmp'`<br>",
				Validators: []validator.List{
					listvalidator.SizeBetween(0, 128),
				},
			},
			"id": schema.Int64Attribute{
				Computed:            true,
				Description:         "The ID of the object to target.",
				MarkdownDescription: "The ID of the object to target.",
			},
			"interface": schema.ListAttribute{
				ElementType:         types.StringType,
				Required:            true,
				Description:         "The interface where packets must originate to match this rule.<br>",
				MarkdownDescription: "The interface where packets must originate to match this rule.<br>",
				Validators: []validator.List{
					listvalidator.SizeBetween(0, 128),
				},
			},
			"ipprotocol": schema.StringAttribute{
				Required:            true,
				Description:         "The IP version(s) this rule applies to.<br>",
				MarkdownDescription: "The IP version(s) this rule applies to.<br>",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"inet",
						"inet6",
						"inet46",
					),
					stringvalidator.LengthBetween(0, 1024),
				},
			},
			"log": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Enable or disable logging of traffic that matches this rule.<br>",
				MarkdownDescription: "Enable or disable logging of traffic that matches this rule.<br>",
			},
			"pdnpipe": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The name of the traffic shaper limiter pipe or queue to use for outgoing traffic.<br>",
				MarkdownDescription: "The name of the traffic shaper limiter pipe or queue to use for outgoing traffic.<br>",
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 1024),
				},
			},
			"protocol": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The IP/transport protocol this rule should match.<br>",
				MarkdownDescription: "The IP/transport protocol this rule should match.<br>",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"tcp",
						"udp",
						"tcp/udp",
						"icmp",
						"esp",
						"ah",
						"gre",
						"ipv6",
						"igmp",
						"pim",
						"ospf",
						"carp",
						"pfsync",
					),
					stringvalidator.LengthBetween(0, 1024),
				},
			},
			"quick": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Apply this action to traffic that matches this rule immediately. This field only applies to floating firewall rules.<br><br>This field is only available when the following conditions are met:<br>- `floating` must be equal to `true`<br>",
				MarkdownDescription: "Apply this action to traffic that matches this rule immediately. This field only applies to floating firewall rules.<br><br>This field is only available when the following conditions are met:<br>- `floating` must be equal to `true`<br>",
			},
			"sched": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The name of an existing firewall schedule to assign to this firewall rule.<br>",
				MarkdownDescription: "The name of an existing firewall schedule to assign to this firewall rule.<br>",
			},
			"source": schema.StringAttribute{
				Required:            true,
				Description:         "The source address this rule applies to. Valid value options are: an existing interface, an IP address, a subnet CIDR, an existing alias, `any`, `(self)`, `l2tp`, `pppoe`. The context of this address can be inverted by prefixing the value with `!`. For interface values, the `:ip`  modifier can be appended to the value to use the interface's IP address instead of its entire subnet.<br>",
				MarkdownDescription: "The source address this rule applies to. Valid value options are: an existing interface, an IP address, a subnet CIDR, an existing alias, `any`, `(self)`, `l2tp`, `pppoe`. The context of this address can be inverted by prefixing the value with `!`. For interface values, the `:ip`  modifier can be appended to the value to use the interface's IP address instead of its entire subnet.<br>",
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 1024),
				},
			},
			"source_port": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The source port this rule applies to. Set to `null` to allow any source port. Valid options are: a TCP/UDP port number, a TCP/UDP port range separated by `:`, an existing port type firewall alias<br><br>This field is only available when the following conditions are met:<br>- `protocol` must be one of [ tcp, udp, tcp/udp ]<br>",
				MarkdownDescription: "The source port this rule applies to. Set to `null` to allow any source port. Valid options are: a TCP/UDP port number, a TCP/UDP port range separated by `:`, an existing port type firewall alias<br><br>This field is only available when the following conditions are met:<br>- `protocol` must be one of [ tcp, udp, tcp/udp ]<br>",
			},
			"statetype": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The state mechanism to use for this firewall rule.<br>",
				MarkdownDescription: "The state mechanism to use for this firewall rule.<br>",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"keep state",
						"sloppy state",
						"synproxy state",
						"none",
					),
					stringvalidator.LengthBetween(0, 1024),
				},
				Default: stringdefault.StaticString("keep state"),
			},
			"tag": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "A packet matching this rule can be marked and this mark used to match on other NAT/filter rules. It is called <br>",
				MarkdownDescription: "A packet matching this rule can be marked and this mark used to match on other NAT/filter rules. It is called <br>",
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 1024),
				},
			},
			"tcp_flags_any": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Allow any TCP flags.<br>",
				MarkdownDescription: "Allow any TCP flags.<br>",
			},
			"tcp_flags_out_of": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "The TCP flags that can be set for this rule to match.<br><br>This field is only available when the following conditions are met:<br>- `tcp_flags_any` must be equal to `false`<br>",
				MarkdownDescription: "The TCP flags that can be set for this rule to match.<br><br>This field is only available when the following conditions are met:<br>- `tcp_flags_any` must be equal to `false`<br>",
				Validators: []validator.List{
					listvalidator.SizeBetween(0, 128),
				},
			},
			"tcp_flags_set": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "The TCP flags that must be set for this rule to match.<br><br>This field is only available when the following conditions are met:<br>- `tcp_flags_any` must be equal to `false`<br>",
				MarkdownDescription: "The TCP flags that must be set for this rule to match.<br><br>This field is only available when the following conditions are met:<br>- `tcp_flags_any` must be equal to `false`<br>",
				Validators: []validator.List{
					listvalidator.SizeBetween(0, 128),
				},
			},
			"tracker": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The internal tracking ID for this firewall rule.<br>",
				MarkdownDescription: "The internal tracking ID for this firewall rule.<br>",
				Validators: []validator.Int64{
					int64validator.Between(0, 99999999999999),
				},
			},
			"type": schema.StringAttribute{
				Required:            true,
				Description:         "The action to take against traffic that matches this rule.<br>",
				MarkdownDescription: "The action to take against traffic that matches this rule.<br>",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"pass",
						"block",
						"reject",
					),
					stringvalidator.LengthBetween(0, 1024),
				},
			},
			"updated_by": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The username and IP of the user who last updated this firewall rule.<br>",
				MarkdownDescription: "The username and IP of the user who last updated this firewall rule.<br>",
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 1024),
				},
				Default: stringdefault.StaticString("@unknown IP (API)"),
			},
			"updated_time": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The unix timestamp of when this firewall rule was original created.<br>",
				MarkdownDescription: "The unix timestamp of when this firewall rule was original created.<br>",
				Validators: []validator.Int64{
					int64validator.Between(0, 99999999999999),
				},
			},
		},
	}
}

type FirewallRuleModel struct {
	Ackqueue         types.String `tfsdk:"ackqueue"`
	ApplyImmediately types.Bool   `tfsdk:"apply_immediately"`
	AssociatedRuleId types.String `tfsdk:"associated_rule_id"`
	CreatedBy        types.String `tfsdk:"created_by"`
	CreatedTime      types.Int64  `tfsdk:"created_time"`
	Defaultqueue     types.String `tfsdk:"defaultqueue"`
	Descr            types.String `tfsdk:"descr"`
	Destination      types.String `tfsdk:"destination"`
	DestinationPort  types.String `tfsdk:"destination_port"`
	Direction        types.String `tfsdk:"direction"`
	Disabled         types.Bool   `tfsdk:"disabled"`
	Dnpipe           types.String `tfsdk:"dnpipe"`
	Floating         types.Bool   `tfsdk:"floating"`
	Gateway          types.String `tfsdk:"gateway"`
	Icmptype         types.List   `tfsdk:"icmptype"`
	Id               types.Int64  `tfsdk:"id"`
	Interface        types.List   `tfsdk:"interface"`
	Ipprotocol       types.String `tfsdk:"ipprotocol"`
	Log              types.Bool   `tfsdk:"log"`
	Pdnpipe          types.String `tfsdk:"pdnpipe"`
	Protocol         types.String `tfsdk:"protocol"`
	Quick            types.Bool   `tfsdk:"quick"`
	Sched            types.String `tfsdk:"sched"`
	Source           types.String `tfsdk:"source"`
	SourcePort       types.String `tfsdk:"source_port"`
	Statetype        types.String `tfsdk:"statetype"`
	Tag              types.String `tfsdk:"tag"`
	TcpFlagsAny      types.Bool   `tfsdk:"tcp_flags_any"`
	TcpFlagsOutOf    types.List   `tfsdk:"tcp_flags_out_of"`
	TcpFlagsSet      types.List   `tfsdk:"tcp_flags_set"`
	Tracker          types.Int64  `tfsdk:"tracker"`
	Type             types.String `tfsdk:"type"`
	UpdatedBy        types.String `tfsdk:"updated_by"`
	UpdatedTime      types.Int64  `tfsdk:"updated_time"`
}
